### ISSUE TITLE
Update bootscript with approriate register/value pairs for programming selected clock chips

### ISSUE THREAD

**Issue by parnao-dl** [parnao-dl/htg-zrf8#1]
The bootscript which is used as a diagnostic tool, to program the clock chips U81, U82, U83 and U78 currently have "bogus" values.  The script must be updated to contain "actual" values that are required for the project.

**Comment by hodgestuff** [comment]
clock chips U81, U82, U83 and U78 are configured using TICS Pro software but this is only draft/preliminary. It may not actually program the correct clock frequencies, etc., but it the software build should work OK.

**Comment by parnao-dl** [comment]
Couple issues:

(1) all registers are now reading zeros
(2) line 362 writes to register 0x15f, which controls the spi readback

However, after deleting line 362 and running the script again, still all registers are reading back zeros:

#-------------------Configure HTG ZRF8 Reference Clocks-------------------------
# bootscript: STARTED
#-------------------------------------------------------------------------------
Scanning for SCI18IS602... Detected SCI18IS602 at bus=2, address=0x2e.
Configuring LMK04832_U78
Configuring LMK04832_U78... done
LMK04832_U78 Configuration
0x000:0x00
0x002:0x00
0x003:0x00
0x004:0x00
0x005:0x00
0x006:0x00
...
0x16c:0x00
0x173:0x00
0x177:0x00
0x182:0x00
0x183:0x00
0x184:0x00
0x185:0x00
0x188:0x00
0x555:0x00

**Comment by hodgestuff** [comment]
Phil,

[image: image.png]

**Comment by parnao-dl** [comment]
Perfect !!  Thanks Jim.  I am reopening this issue for now

**Comment by parnao-dl** [comment]
Finished updates to the bootscript and released.

**Comment by hodgestuff** [comment]
Fantastic, Phil. Congrats!

Have you exercised the 9 LEDs?
